---
AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/SingleLineBlockParams:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Exclude:
    - spec/**/*_spec.rb
